name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  APP_LOCATION: "/" # App source code path
  API_LOCATION: ".output/server" # Api source code path - optional
  OUTPUT_LOCATION: ".output/public" # Built app content directory - optional

jobs:
  Deploy-Test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy to Test
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.WEB_APP_DEPLOYMENT_TOKEN_TEST }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
        env:
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_REDIRECT_URI: ${{ secrets.AUTH0_REDIRECT_URI }}
          PRODUCTS_BASE_URI: ${{ secrets.PRODUCTS_BASE_URI }}

  Deploy-Production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: Deploy-Test
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy to Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.WEB_APP_DEPLOYMENT_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
        env:
          AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
          AUTH0_CLIENT_ID: ${{ vars.AUTH0_CLIENT_ID }}
          AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
          AUTH0_REDIRECT_URI: ${{ vars.AUTH0_REDIRECT_URI }}
          PRODUCTS_BASE_URI: ${{ vars.PRODUCTS_BASE_URI }}
